# Generated by Django 5.2 on 2025-07-08 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoCono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('variante', models.CharField(choices=[('Carnívoro', 'Carnívoro'), ('Vegetariano', 'Vegetariano'), ('Saludable', 'Saludable')], max_length=20)),
                ('toppings', models.JSONField(blank=True, default=list)),
                ('tamanio_cono', models.CharField(choices=[('Pequeño', 'Pequeño'), ('Mediano', 'Mediano'), ('Grande', 'Grande')], max_length=20)),
                ('fecha_pedido', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pedido de Cono',
                'verbose_name_plural': 'Pedidos de Conos',
                'ordering': ['-fecha_pedido'],
            },
        ),
    ]
