# Generated by Django 5.2 on 2025-07-08 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_conos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocono',
            name='cliente',
            field=models.CharField(max_length=100, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='pedidocono',
            name='tamanio_cono',
            field=models.CharField(choices=[('Pequeño', 'Pequeño'), ('Mediano', 'Mediano'), ('Grande', 'Grande')], max_length=10),
        ),
    ]
